export function createPrAgentEnvironment(bindings) {
  const {
    CF_ACCESS_CLIENT_ID,
    CF_ACCESS_CLIENT_SECRET,
    CLYDE_BASE_URL,
    GITHUB_APP_ID,
    GITHUB_BOT_LOGIN,
    GITHUB_PRIVATE_KEY,
    GITHUB_WEBHOOK_SECRET,
    OPENAI_KEY,
    PORT,
    REVIEW_MAX_UNRESOLVED_COMMENTS,
    REVIEW_MIN_IMPORTANCE,
    REVIEW_TIMEOUT,
    REVIEW_WORKERS,
  } = bindings;

  return {
    CF_ACCESS_CLIENT_ID,
    CF_ACCESS_CLIENT_SECRET,
    CLYDE_API_KEY: OPENAI_KEY,
    CLYDE_BASE_URL,
    GITHUB_APP_ID,
    GITHUB_BOT_LOGIN,
    GITHUB_PRIVATE_KEY,
    GITHUB_WEBHOOK_SECRET,
    PORT,
    REVIEW_MAX_UNRESOLVED_COMMENTS,
    REVIEW_MIN_IMPORTANCE,
    REVIEW_TIMEOUT,
    REVIEW_WORKERS,
  };
}
