// The container receives only the bindings named here. A binding that is not
// destructured and re-emitted never reaches the service, so a new variable must
// be added in both places.
export function createPrAgentEnvironment(bindings) {
  const {
    CF_ACCESS_CLIENT_ID,
    CF_ACCESS_CLIENT_SECRET,
    CLYDE_BASE_URL,
    FALLBACK_API_KEY,
    FALLBACK_BASE_URL,
    FALLBACK_CF_ACCESS_CLIENT_ID,
    FALLBACK_CF_ACCESS_CLIENT_SECRET,
    FALLBACK_MODEL,
    FALLBACK_ON,
    GITHUB_APP_ID,
    GITHUB_BOT_LOGIN,
    GITHUB_PRIVATE_KEY,
    GITHUB_WEBHOOK_SECRET,
    LOG_FORWARD_URL,
    OPENAI_KEY,
    PORT,
    REVIEW_CHUNK_TIMEOUT,
    REVIEW_MAX_CHUNKS,
    REVIEW_MAX_FILES,
    REVIEW_MIN_IMPORTANCE,
    REVIEW_MODEL,
    REVIEW_WORKERS,
  } = bindings;

  return {
    CF_ACCESS_CLIENT_ID,
    CF_ACCESS_CLIENT_SECRET,
    CLYDE_API_KEY: OPENAI_KEY,
    CLYDE_BASE_URL,
    FALLBACK_API_KEY,
    FALLBACK_BASE_URL,
    FALLBACK_CF_ACCESS_CLIENT_ID,
    FALLBACK_CF_ACCESS_CLIENT_SECRET,
    FALLBACK_MODEL,
    FALLBACK_ON,
    GITHUB_APP_ID,
    GITHUB_BOT_LOGIN,
    GITHUB_PRIVATE_KEY,
    GITHUB_WEBHOOK_SECRET,
    LOG_FORWARD_URL,
    PORT,
    REVIEW_CHUNK_TIMEOUT,
    REVIEW_MAX_CHUNKS,
    REVIEW_MAX_FILES,
    REVIEW_MIN_IMPORTANCE,
    REVIEW_MODEL,
    REVIEW_WORKERS,
  };
}
